//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProd { get; set; }
        public string nameProd { get; set; }
        public long barcodeNumber { get; set; }
    }
}
